-- +goose Up
CREATE TABLE wallets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wallet_id VARCHAR(255) NOT NULL UNIQUE,
    owner_id INT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

-- +goose Down
DROP TABLE wallets;
